name: feet-segmentation-env
dependencies:
  - python=3.8
  - numpy=1.21
  - cudatoolkit=10.2
  - cudnn=7.6
  - pytorch
  - pip
  - pip:
    - tqdm
    - opencv-python
    - matplotlib
    - albumentations
    - seaborn
    - depthai